services:
  openchamber:
    container_name: openchamber
    image: arranhs/openchamber
    build:
      context: .
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ~/openchamber/workspace:/home/opencode/workspace # code files
      - ~/openchamber/.config/opencode:/home/opencode/.config/opencode # opencode config
      - ~/openchamber/.local/share/opencode:/home/opencode/.local/share/opencode # ooencode sessions
      - ~/.gitconfig:/home/opencode/.gitconfig:ro # git config
      - ~/.config/gh/hosts.yml:/home/opencode/.config/gh/hosts.yml:ro # github cli config
    environment:
      - TZ=Europe/London
