services:
  openchamber:
    container_name: openchamber
    image: arranhs/openchamber
    build:
      context: .
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ~/openchamber/workspace:/home/opencode/workspace # Code files
      - ~/openchamber/.config/opencode:/home/opencode/.config/opencode # Opencode config
      - ~/openchamber/.local/share/opencode:/home/opencode/.local/share/opencode # Opencode sessions
      - ~/openchamber/.gitconfig:/home/opencode/.gitconfig # Git config
    environment:
      - TZ=Europe/London
